#!/usr/bin/env python
# encoding: utf-8
#
# Copyright (c) 2012, Peter Hillerström <peter.hillerstrom@gmail.com>
# All rights reserved. This software is licensed under 3-clause BSD license.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# This module generates ANSI character codes for terminals.
# See: http://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes

import sys
import time

sys.path.append('../lib/')

from lib import *

if __name__ != '__main__':
    __name__ = 'prism'

def tail():
    fi = fileinput.input()
    while True:
        try:
            line = fi.readline()
            if not line:
                #print "Sleeping"
                time.sleep(0.25)
                continue
            yield colourise(line.rstrip())
        except KeyboardInterrupt:
            fi.close()
            quit()

if __name__ in ['__main__', 'prism']:
    print nameplate()

    if len(sys.argv) == 0:
        print usage()
        quit()

    gen = tail()
    while True:
        print next(gen)
